services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cozie_db
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
